# -*- coding: utf-8 -*-
"""kmeansirisproject6 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tA2T5_63jIez8fmKzfWT7rn5NhWtdxT7
"""

!
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

# ------------------ PAGE ------------------
st.set_page_config(
    page_title="Iris K-Means Clustering",
    page_icon="🌸",
    layout="wide"
)

st.title("🌸 Iris Flower Clustering using K-Means")
st.write("This project groups Iris flowers into 3 clusters using Petal Length and Petal Width."
        "PROJECT made by Aditi Srivastava with roll no.240122155005)

# ------------------ IMAGE ------------------
try:
    st.image("iris(2).png", width=350)
except:
    st.info("Iris flower image not found.")

# ------------------ LOAD DATA ------------------
iris = load_iris()

df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

df = df[['petal length (cm)', 'petal width (cm)']]

# ------------------ SCALE ------------------
scaler = MinMaxScaler()

scaled = scaler.fit_transform(df)

# ------------------ MODEL ------------------
model = KMeans(
    n_clusters=3,
    random_state=42,
    n_init=10
)

clusters = model.fit_predict(scaled)

df["Cluster"] = clusters

# ------------------ SIDEBAR ------------------
st.sidebar.header("Flower Features")

length = st.sidebar.slider(
    "Petal Length",
    1.0,
    7.0,
    4.5
)

width = st.sidebar.slider(
    "Petal Width",
    0.1,
    2.5,
    1.4
)

sample = scaler.transform([[length, width]])

prediction = model.predict(sample)[0]

st.sidebar.success(f"Predicted Cluster : {prediction}")

# ------------------ DATASET ------------------
st.subheader("Dataset")

st.dataframe(df.head(10), use_container_width=True)

# ------------------ CLUSTER GRAPH ------------------
st.subheader("Cluster Visualization")

fig, ax = plt.subplots(figsize=(7,5))

colors = ["red", "green", "blue"]

for i in range(3):
    temp = df[df.Cluster == i]

    ax.scatter(
        temp["petal length (cm)"],
        temp["petal width (cm)"],
        color=colors[i],
        label=f"Cluster {i}"
    )

centers = scaler.inverse_transform(model.cluster_centers_)

ax.scatter(
    centers[:,0],
    centers[:,1],
    marker="*",
    s=300,
    color="black",
    label="Centroids"
)

ax.scatter(
    length,
    width,
    marker="X",
    s=220,
    color="orange",
    label="Your Input"
)

ax.set_xlabel("Petal Length")
ax.set_ylabel("Petal Width")
ax.legend()

st.pyplot(fig)

# ------------------ ELBOW ------------------
st.subheader("Elbow Method")

sse = []

for k in range(1,11):
    km = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    km.fit(scaled)

    sse.append(km.inertia_)

fig2, ax2 = plt.subplots(figsize=(6,4))

ax2.plot(range(1,11), sse, marker="o")

ax2.set_xlabel("Number of Clusters")
ax2.set_ylabel("SSE")
ax2.grid(True)

st.pyplot(fig2)

# ------------------ SUMMARY ------------------
st.subheader("Project Information")

st.success("""
Algorithm : K-Means Clustering

Dataset : Iris Dataset

Features Used :
• Petal Length
• Petal Width

Optimal Number of Clusters : 3
""")
